name: 'Docker Build'
description: 'Builds a Docker image'
inputs:
  path_dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  image_name:
    description: 'Name of the Docker image'
    required: true
  tag_name:
    description: 'Tag for the Docker image'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
