name: main
description: perform action
inputs:
  Hello_World:
    description: ""
    required: true
    default: "default value"
runs:
  using: composite
  steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag academy:$(date +%s)
      shell: bash
      
    - name : list the docker images
      run: docker images
      shell: bash
      