name: new DockerImage
description: 'Builds a new Docker image'
inputs:
  input-description:
    description: " input-description "
    required: true
    default: "8080:8080"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      shell: bash
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    

      