name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
 
    - name: Lists the docker images
      run: docker images
    - uses: xic-let/academy/.github/actions/docker_build@main
      with:
        path_dockerfile: './Dockerfile'
        image_name: 'academy'
        tag_name: 'latest'


